# Local

# URL PRO BD 
spring.datasource.url=jdbc:postgresql://localhost:5432/projetoMilitar

# USUÁRIO DO BANCO DE DADOS
spring.datasource.username=postgres
# SENHA DO USUÁRIO DO BANCO DE DADOS
spring.datasource.password=postgres
# DRIVER JDBC
spring.datasource.driverClassName=org.postgresql.Driver
# MOSTRA AS CONSULTAS NO CONSOLE
spring.jpa.show-sql=true
# PADRONIZA A LINGUAGEM SQL DE UM SGBD ESPECIFICO
spring.jpa.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=none

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Habilitar o CORS de forma global
cors.originPatterns=http://localhost:8080,http://localhost:8081,http://localhost:19006,http://localhost:3000


# So pra garantir que n vai ter problema com columns maiusculas e minusculas na conversão do hibernate
# (Essa estratégia serve pra mesmo com o @Column minúsculo, o Hibernate 7 pode tentar converter pra snake_case
# se a strategy estiver ativa)
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
