CREATE TABLE IF NOT EXISTS soldados (
    idSoldados SERIAL PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    identificador VARCHAR(20) UNIQUE NOT NULL,
    patente VARCHAR(50) NOT NULL,
    pelotao VARCHAR(20) NOT NULL CHECK (pelotao IN ('SELVA', 'TANQUE', 'JEEP', 'PARAQUEDISTA')),
    funcao VARCHAR(100),
    data_ingresso DATE,
    status VARCHAR(10) DEFAULT 'ATIVO' CHECK (status IN ('ATIVO', 'LICENCA', 'INATIVO')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);